server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery-service?createDatabaseIfNotExist=true
    username: root
    password: 123456a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: delivery-service
