server:
  port: 5001
  servlet:
    context-path: '/api'
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true"
    username: root
    password: 123456a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: order-service
other:
  inventory-service-url: http://localhost:5000

