version: "3.9"
name: G18
services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      retries: 5
      start_period: 10s

  # IndentifyService:
  #   build:
  #     context: ./IndentifyService
  #     dockerfile: Dockerfile
  #   container_name: IndentifyService
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   ports:
  #     - "8080:8080"

  # ProfileService:
  #   build:
  #     context: ./ProfileService
  #     dockerfile: Dockerfile
  #   container_name: ProfileService
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   ports:
  #     - "8088:8088"
